### ISSUE TITLE
*.answer::before and p.advice::before content not rendered properly

### ISSUE THREAD

**Issue by janslifka** [DataStewardshipWizard/dsw-common#95]
Moved from DataStewardshipWizard/dsw-client#28

> In exported questionnaire html file, the content in *.answer::before and p.advice::before renders as seen in screenshot below.
>
> <img width="1273" alt="screen shot 2018-07-02 at 15 43 25" src="https://user-images.githubusercontent.com/208443/42167782-593e3d9a-7e0f-11e8-9fb6-81bcea892983.png">

**Comment by MarekSuchanek** [comment]
Former report was by @mkuzak?

This is probably not a bug. It renders OK for me, we use Unicode characters...

![screenshot_2018-07-10_10-28-35](https://user-images.githubusercontent.com/9638527/42498326-2d16d0b0-842c-11e8-96a0-ce3b1e1a365c.png)

Could you please test in your `.html` file if helps when you replace this:

```css
div.answer-option > p.advice::before {
  content : " ⓘ  ";
}
```

with this:

```css
div.answer-option > p.advice::before {
  content : " &#9432;  ";
}
```
